import { Transaction } from '../types';

// Generate mock transactions based on the aggregated data
export const mockTransactions: Transaction[] = [
  {
    id: '1',
    date: '2025-09-20',
    merchant: 'Amazon.com',
    category: 'Shopping',
    account: 'Amazon Prime',
    amount: -20.27,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '2',
    date: '2025-09-19',
    merchant: 'Amazon Marketplace N',
    category: 'Shopping',
    account: 'Amazon Business 2002',
    amount: -141.97,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '3',
    date: '2025-09-19',
    merchant: 'Myia.com-us',
    category: 'Other',
    account: 'Freedom - Emu 7539',
    amount: -114.99,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '4',
    date: '2025-09-18',
    merchant: 'Dunkin\' Donuts',
    category: 'Restaurants',
    account: 'Freedom - Emu 7539',
    amount: -14.99,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '5',
    date: '2025-09-18',
    merchant: 'Chick-fil-a',
    category: 'Restaurants',
    account: 'Freedom - Emu 7539',
    amount: -38.95,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '6',
    date: '2025-09-18',
    merchant: 'Car Wash',
    category: 'Auto Misc',
    account: 'Freedom - Emu 7539',
    amount: -15.00,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '7',
    date: '2025-09-18',
    merchant: 'Castle Skateland',
    category: 'Restaurants',
    account: 'Freedom - Emu 7539',
    amount: -115.60,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '8',
    date: '2025-09-17',
    merchant: 'Kroger',
    category: 'Groceries',
    account: 'Sapphire 6823',
    amount: -24.15,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '9',
    date: '2025-09-17',
    merchant: 'Chase Credit Crd Autopay',
    category: 'Other',
    account: 'PerChecking 9251',
    amount: -12298.98,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '10',
    date: '2025-09-16',
    merchant: 'Credit Return- Online Payment',
    category: 'Auto Misc',
    account: 'Patelco Credit Union',
    amount: 1408.53,
    status: 'posted',
    type: 'credit',
  },
  {
    id: '11',
    date: '2025-09-13',
    merchant: 'Pt *cincinnati Children\'s',
    category: 'Other',
    account: 'Freedom - Emu 7539',
    amount: -145.47,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '12',
    date: '2025-09-13',
    merchant: 'Gcww-ez-pay Utilities',
    category: 'Utility',
    account: 'PerChecking 9251',
    amount: -183.58,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '13',
    date: '2025-09-15',
    merchant: 'Interest Payment',
    category: 'Other',
    account: 'PerSaving 8101',
    amount: 10.02,
    status: 'posted',
    type: 'credit',
  },
  {
    id: '14',
    date: '2025-09-15',
    merchant: 'Tihealth Sbo',
    category: 'Other',
    account: 'Freedom - Emu 7539',
    amount: -136.98,
    status: 'posted',
    type: 'debit',
  },
  {
    id: '15',
    date: '2025-09-14',
    merchant: 'Chick-fil-a',
    category: 'Restaurants',
    account: 'Freedom - Emu 7539',
    amount: -8.28,
    status: 'posted',
    type: 'debit',
  },
];
